name: RSpec

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@latest

    - name: Verify Firefox installation
      run: firefox --version

    - name: Run unit tests
      run: bundle exec rspec --exclude-pattern "spec/integration/**/*_spec.rb"

    - name: Run integration tests
      run: bundle exec rspec spec/integration/
      env:
        HEADLESS: true

    - name: Run RuboCop
      run: bundle exec rubocop
      continue-on-error: true
