name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ['3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install Firefox (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Install Firefox (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install --cask firefox

    - name: Verify Firefox installation
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          firefox --version
        elif [ "$RUNNER_OS" == "macOS" ]; then
          /Applications/Firefox.app/Contents/MacOS/firefox --version
        fi

    - name: Run unit tests
      run: bundle exec rspec --exclude-pattern "spec/integration/**/*_spec.rb"

    - name: Run integration tests
      run: bundle exec rspec spec/integration/
      env:
        HEADLESS: true

    - name: Run RuboCop
      run: bundle exec rubocop
      continue-on-error: true
